version: "0.8.5"
services:
    postgredb:
        build:
            context: ./docker/postgresql
            dockerfile: Dockerfile
       # environment: POSTGRES_PASSWORD = devpass
        #  volumes:
        #      ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports: [5432:5432]
    web:
        build:
            contex: ./
            dockerfile: Dockerfile
        # volumes:
        # depends_on: 
        #     - postgredb

    


